blank_issues_enabled: false
contact_links:
  - name: 🚀 Feature request
    url: https://pact.canny.io/
    about: The Canny board to send us feature requests, vote and measure the interest of users. Useful to submit a feature request when you have an idea but no concrete API design proposal.
  - name: ❓ Simple question - Slack chat
    url: https://slack.pact.io/
    about: This issue tracker is not for technical support. Please use our Slack group, and ask the community for help.
  - name: ❓ Simple question - Stack Overflow
    url: https://stackoverflow.com/questions/tagged/pact
    about: This issue tracker is not for technical support. Please use Stack Overflow, and ask the community for help.
  - name: ❓ Advanced question - GitHub Discussions
    url: https://github.com/pact-foundation/pact-specification/discussions/
    about: Use GitHub Discussions for advanced and unanswered questions only, requiring a maintainer's answer. Make sure the question wasn't already asked.
  - name: ❓ Advanced question - GitHub Discussions
    url: https://github.com/safdotdev/.github/security/advisories/new
    about: Use GitHub Discussions for advanced and unanswered questions only, requiring a maintainer's answer. Make sure the question wasn't already asked.