---
name: "Release gem"

on:
  repository_dispatch:
    types:
      - release-triggered

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pact-foundation/release-gem@v1
        env:
          GEM_HOST_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          INCREMENT: "${{ github.event.client_payload.increment }}"
