name: Apply Pact Foundation Label Policy
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  mirror-labels:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    name: manage-your-labels
    steps:
      - uses: actions/checkout@v2
      - uses: pact-foundation/manage-your-labels@v0.0.1