name: SmartBear Supported Issue Comment Created

# Example of trigger for this workflow:
#
# on:
#   issue_comment:
#     types:
#       - created

on:
  workflow_call:

jobs:
  jira:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '/smartbear-supported issue' }}
    steps:
    - run: echo ${{ github.event.comment.body }}
    
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.SMARTBEAR_JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.SMARTBEAR_JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.SMARTBEAR_JIRA_API_TOKEN }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
     
    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.1.0
      with:
        jql: 'summary ~ "${{ github.event.repository.name }}#${{ github.event.issue.number }}:" AND project=${{ vars.SMARTBEAR_JIRA_PROJECT }}'
    
    - name: Log
      run: echo "Found issue ${{ steps.search.outputs.issue }}"
    
    - name: Create
      id: create
      if: steps.search.outputs.issue == ''
      uses: atlassian/gajira-create@v3
      with:
        project: ${{ secrets.SMARTBEAR_JIRA_PROJECT }}
        issuetype: Task
        summary: '${{ github.event.repository.name }}#${{ github.event.issue.number }}: ${{ github.event.issue.title }}'
        description: |
          *Issue Link:* ${{ github.event.issue.html_url }}
          
          ${{ github.event.issue.body }}
        fields: '{"customfield_10006": ${{ toJSON(secrets.SMARTBEAR_JIRA_EPIC_TICKET) }}, "customfield_17401":{"value":${{ toJSON( secrets.SMARTBEAR_JIRA_LAYER_CAKE )}}}}'
          
    - name: Add Comment 
      if: steps.search.outputs.issue == '' && steps.create.outputs.issue != ''
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🤖 Great news! We've labeled this issue as <i>smartbear-supported</i> and created a tracking ticket in PactFlow's Jira (<a href='https://smartbear.atlassian.net/browse/${{steps.create.outputs.issue}}'><code>${{steps.create.outputs.issue}}</code></a>). We'll keep work public and post updates here. Meanwhile, feel free to check out our <a href='https://docs.pact.io/help/smartbear'>docs</a>. Thanks for your patience!"
          })

    - name: Add Jira Label
      uses: actions-ecosystem/action-add-labels@v1
      if: steps.search.outputs.issue == '' && steps.create.outputs.issue != ''
      with:
        labels: smartbear-supported
