name: Add New Issues to Triage Board

on:
  workflow_call:

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/orgs/pact-foundation/projects/16
          github-token: ${{ secrets.TRIAGE_PROJECT_ISSUE_TOKEN }}
          # If needed, can use 
          labeled: triage
          label-operator: OR
 